version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: payroll_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: MayHoaThoDB@12345!
      MYSQL_DATABASE: quan_ly_luong
      MYSQL_USER: payroll_user
      MYSQL_PASSWORD: payroll_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - payroll_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: payroll_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: MayHoaThoDB@12345!
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - payroll_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    container_name: payroll_backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 4000
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: MayHoaThoDB@12345!
      DB_NAME: quan_ly_luong
      DB_PORT: 3306
      JWT_SECRET: your-super-secret-jwt-key-here-change-in-production
      JWT_EXPIRES_IN: 24h
      FRONTEND_URL: http://localhost:5173
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend_uploads:/app/uploads
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - payroll_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    container_name: payroll_frontend
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://localhost:4000/api
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - payroll_network

volumes:
  mysql_data:
    driver: local
  backend_uploads:
    driver: local

networks:
  payroll_network:
    driver: bridge
